feat: implemented back-end for creating news and sending them to all …
PSW-Organization-8/pharmacy-back pull request #3
Opened 2021-11-15 20:15 UTC by MatijaUskokovic

…registrated hospitals

build: added test project and initialized classes needed for writing integrated test for offering news to hospitals

test: implemented integration test for offering actions and news to hospitals

feat: implemented end point for creating news and sending them to all subscribed hospitals

2021-11-15 20:51 UTC, mmitic99 approved these changes

2021-11-16 09:15 UTC, djordjekrsmanovic commented on PharmacyInformationSystem/Pharmacy/Service/Interface/IActionsAndNewsService.cs
> +        public News CreateAndSendNewsToAllSubscribedHospitals(News newNews);
You dont't need **public** qualifier for interface methods

2021-11-16 09:19 UTC, djordjekrsmanovic requested changes

2021-11-16 09:19 UTC, djordjekrsmanovic commented on PharmacyInformationSystem/Pharmacy/Service/Interface/ISendingNewsService.cs
> +        public void SendNews(News newNews);
You do not need **public** qualifier for interface method

2021-11-16 11:11 UTC, djordjekrsmanovic approved these changes

2021-11-16 11:13 UTC, merged