feat: emailng when delivered urgent procurement of medications
PSW-Organization-8/pharmacy-back pull request #46
Opened 2022-01-11 18:06 UTC by mmitic99

2022-01-11 19:04 UTC, MatijaUskokovic approved these changes

2022-01-13 15:48 UTC, djordjekrsmanovic requested changes

2022-01-13 15:48 UTC, djordjekrsmanovic commented on PharmacyInformationSystem/Pharmacy/Service/EmailService.cs
> +            emailCredentials = new NetworkCredential("psworganisation8@outlook.com", "pswFtnOrganisation8");
Need to replace email and password with env variables.
You can put default values for email and password.
But it is more flexible with env variables and sonar cloud code analysis will be successfull

2022-01-13 17:26 UTC, djordjekrsmanovic approved these changes

2022-01-13 17:32 UTC, merged